### ISSUE TITLE
puppeteer@10.4.0: Version no longer supported. 

### ISSUE THREAD

**Issue by loec01** [sebbo2002/fileee-backup-downloader#65]
I just try to install the script on top of an existing openmediavault installation. 
I did install puppeteer using "npm I puppeteer", so it should be the newest version. However, when trying to install the fileee-backup script, I get the following error message

npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest

I can't figure out how to upgrade puppeteer, nor to continue running the script.
Any suggestions are highly appreciated!

Thanks
Tobias

**Comment by sebbo2002** [comment]
Oh, that should not be so, of course. I'll take a look tomorrow, thanks for letting me know.

**Comment by sebbo2002** [comment]
Could you try version [v2.0.3-develop.1](https://github.com/sebbo2002/fileee-backup-downloader/releases/tag/v2.0.3-develop.1)? There should be the current puppeteer in it.

**Comment by sebbo2002** [comment]
I just released v2.0.3 which should work. Thanks for your report.

**Comment by sebbo2002** [comment]
No, it doesn't look like this is a mistake on my part. The permissions in the `/usr/lib/node_modules` folder just weren't enough, so you had to install the script again with root permissions. [Here](https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md) is a good description how you can change that in the future.
